<?php

/**
 *
 * @copyright  2010-2011 izend.org
 * @version    6
 * @link       http://www.izend.org
 */
?>
<?php if (!empty($contact_page) or !empty($user_page) or !empty($nobody_page) or !empty($account_page) or !empty($edit_page) or !empty($view_page) or !empty($validate_page) or !empty($admin_page)): ?>
<ul id="bannermenu" class="menu menubar">
<?php if (!empty($contact_page)): ?>
<li><a class="btn_mail" href="<?php echo $contact_page; ?>" rel="nofollow" title="Nous contacter"><i class="fa fa-lg fa-fw fa-envelope" aria-hidden="true" aria-label="Nous contacter"></i></a></li>
<?php endif; ?>
<?php if (!empty($user_page)): ?>
<li><a class="btn_login" href="<?php echo $user_page; ?>" rel="nofollow" title="Votre compte"><i class="fa fa-lg fa-fw fa-user" aria-hidden="true" aria-label="Votre compte"></i></a></li>
<?php endif; ?>
<?php if (!empty($nobody_page)): ?>
<li><a class="btn_logout" href="<?php echo $nobody_page; ?>" rel="nofollow" title="Déconnexion"><i class="fa fa-lg fa-fw fa-power-off" aria-hidden="true" aria-label="Déconnexion"></i></a></li>
<?php endif; ?>
<?php if (!empty($account_page)): ?>
<li><a class="btn_account" href="<?php echo $account_page; ?>" rel="nofollow" title="Votre compte"><i class="fa fa-lg fa-fw fa-user" aria-hidden="true" aria-label="Votre compte"></i></a></li>
<?php endif; ?>
<?php if (!empty($edit_page)): ?>
<li><a class="btn_edit" href="<?php echo $edit_page; ?>" title="Éditer" rel="nofollow"><i class="fa fa-lg fa-fw fa-pen" aria-hidden="true" aria-label="Éditer"></i></a></li>
<?php elseif ($view_page): ?>
<li><a class="btn_view" href="<?php echo $view_page; ?>" title="Voir" rel="nofollow"><i class="fa fa-lg fa-fw fa-globe" aria-hidden="true" aria-label="Voir"></i></a></li>
<?php endif; ?>
<?php if (!empty($validate_page)): ?>
<li><a class="btn_validate" href="http://validator.w3.org/check?uri=<?php echo $base_root . $validate_page; ?>" target="validator.w3.org" rel="nofollow" title="Valider"><i class="fa fa-lg fa-fw fa-check" aria-hidden="true" aria-label="Valider"></i></a></li>
<?php endif; ?>
<?php if (!empty($admin_page)): ?>
<li><a class="btn_admin" href="<?php echo $admin_page; ?>" rel="nofollow" title="Gérer"><i class="fa fa-lg fa-fw fa-cog" aria-hidden="true" aria-label="Gérer"></i></a></li>
<?php endif; ?>
</ul>
<?php endif; ?>
