<?php

/**
 *
 * @copyright  2010-2014 izend.org
 * @version    12
 * @link       http://www.izend.org
 */
?>
<div id="footer">
<?php if (!empty($languages)): ?>
<?php echo $languages; ?>
<?php endif; ?>
<p>
&copy;&nbsp;<?php echo idate('Y'); ?> <?php echo $sitename, PHP_EOL; ?>
<span class="hidden">
<span class="bullet">&bull;</span>
<a href="http://www.izend.org">iZend</a>
</span>
<?php if (!empty($contact_page) or !empty($newsletter_page) or !empty($nobody_page) or !empty($account_page) or !empty($user_page) or !empty($admin_page)): ?>
<span id="footermenu">
<?php if (!empty($contact_page)): ?>
<span class="bullet">&bull;</span>
<a href="<?php echo $contact_page; ?>" rel="nofollow" title="Contact us">Contact</a>
<?php endif; ?>
<?php if (!empty($newsletter_page)): ?>
<span class="bullet">&bull;</span>
<a href="<?php echo $newsletter_page; ?>" rel="nofollow" title="Follow us">Newsletter</a>
<?php endif; ?>
<?php if (!empty($nobody_page) or !empty($account_page) or !empty($user_page) or !empty($admin_page)): ?>
<span class="bullet">&bull;</span>
<span class="controls">
<?php if (!empty($nobody_page)): ?>
<a href="<?php echo $nobody_page; ?>" rel="nofollow" title="Disconnect"><i class="fa fa-fw fa-power-off" aria-hidden="true" aria-label="Disconnect"></i></a>
<?php endif; ?>
<?php if (!empty($account_page)): ?>
<a href="<?php echo $account_page; ?>" rel="nofollow" title="Your account"><i class="fa fa-fw fa-user" aria-hidden="true" aria-label="Your account"></i></a>
<?php endif; ?>
<?php if (!empty($user_page)): ?>
<a href="<?php echo $user_page; ?>" rel="nofollow" title="Your account"><i class="fa fa-fw fa-user" aria-hidden="true" aria-label="Your account"></i></a>
<?php endif; ?>
<?php if (!empty($admin_page)): ?>
<a href="<?php echo $admin_page; ?>" rel="nofollow" title="Manage"><i class="fa fa-fw fa-cog" aria-hidden="true" aria-label="Manage"></i></a>
<?php endif; ?>
</span>
<?php endif; ?>
</span>
<?php endif; ?>
</p>
</div>
